### PR TITLE
Incorrect value type is generated for speudoboolean field

### PR DESCRIPTION
**Pull request by Oberon82**

### CODE REVIEW

**Comment by madorin** [comment]
Hello,
Can you explain please, what is the reason/fix of "boolean" patch?

**Comment by Oberon82** [comment]
GenerateSQLTextNoParams is used when AutoUpdateOptions.UseExecuteBlock = True and CachedUpdates = True. Fib generates SQL to update or insert record. But if SmallInt or Integer field is created as TFIBBooleanField (if field domain name contains substring "boolean") then the incorrect value (TRUE or FALSE instead of 1 or 0) is generated for this field. FB 2.5 don't support TRUE and FALSE constants. Also, you can't use TRUE and FALSE to update smallint fields. Sorry about my english.

**Comment by madorin** [comment]
Oberon82, this fix seems to be not so trivial, and unfortunately i can't accept it.

Some ideas to improve it:
- it should take in account PrepareOptions.psUseBooleanField flag.
- invoking each time IsFieldTrueBoolean that do an extra query seems costly

Decision to simulate a boolean or not for specific field is done with TpFIBTableInfoCollect.GetFieldInfo and TpFIBFieldInfo.CanBeBoolean functions. See procedure TFIBCustomDataSet.InternalInitFieldDefs;

I think we should check if type is simulated or not using TFIBDataSet.vFieldDescrList[Index].fdDataType to check for SQL_BOOLEAN, FB3_SQL_BOOLEAN. See how it is done in procedure TFIBCustomDataSet.SetQueryParams. It can be done in FieldValueToStr too, using the same logic.

I see you are from RF, so I understand pretty well Russian.

**Comment by madorin** [comment]
Closed due to inactivity. FB3 already have native boolean type support.

**Pull request closed without merging**
