### PR TITLE
added bpl folder to gitignore

### PR DESCRIPTION
**Pull request by wadealer**

### CODE REVIEW

**Comment by madorin** [comment]
@wadealer , Package output folder is not changed in packages, so generated bpl's and dcp's should be placed into $(BDSCOMMONDIR)\Bpl and $(BDSCOMMONDIR)\Dcp accordingly.
Have you found any packages with just Bpl as output directory?

**Comment by wadealer** [comment]
FIBPlusEditors2011 has package output directory set as 'bpl'. Maybe others too.

**Comment by madorin** [comment]
Some of them have Devrace build configuration, so it has bpl as output path.
I'm not an advocate of separate bpl's output for custom packages, but ok, will merge it.

**Comment by wadealer** [comment]
Tnx.

**Pull request closed without merging**
